os:
  - osx
addons:
  homebrew:
    packages:
    - freexl
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef --deps-only install .
script:
  - PERL6LIB=lib prove --ext .t --ext .t6 -v -r --exec=perl6 t/
sudo: false
